name: lsmods
version: "1.0.0"
summary: LSMODS let you inspect loaded kernel modules with descriptions
description: |
  Show all loaded kernel modules with descriptions
grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.15.4
  lsmods:
    plugin: go
    go-importpath: github.com/bieli/lsmods
    source: .
    source-type: git
    after: [go]

apps:
  lsmods:
    command: bin/lsmods
